- name: copy concepts
  copy:
    src: concepts
    dest: "{{ openmrs_install_dir }}/configuration"
    owner: bahmni

- name: copy forms
  copy:
    src: bahmniforms
    dest: "{{ openmrs_install_dir }}/configuration"
    owner: bahmni

- name: create translations directory
  file:
    path: "{{ bahmni_forms_translations_dir }}"
    state: directory

- name: copy form translations
  vars:
    bahmni_form_dir: "{{ openmrs_install_dir }}/configuration/bahmniforms"
  script:
    cmd: "publish_translations.py {{ bahmni_form_dir }} {{ bahmni_forms_translations_dir }}"

- name: allow all users to modify translations
  file:
    path: "{{ bahmni_forms_translations_dir }}"
    recurse: yes
    owner: bahmni
    mode: a+rwx

- name: download the initializer version 2.0.0
  get_url:
    url: https://openmrs.jfrog.io/artifactory/mekom-solutions-cache/org/openmrs/module/initializer-omod/2.0.0/initializer-omod-2.0.0.jar
    dest:  "{{ openmrs_install_dir }}/modules/initializer-2.0.0.omod"
    owner: bahmni
    group: bahmni

- name: download the ie apps version 1.0.0
  get_url:
    url: https://openmrs.jfrog.io/artifactory/mekom-solutions-cache/org/bahmni/module/bahmni.ie.apps-omod/1.0.0/bahmni.ie.apps-omod-1.0.0.jar
    dest:  "{{ openmrs_install_dir }}/modules/bahmni.ie.apps-1.0.0.omod"
    owner: bahmni
    group: bahmni

# TODO: refactor later. avoid database conflicts
- name: update concept sources
  vars:
     update_script: "{{ lookup('file', 'concept_sources_helper.sql') }}"
  shell: echo {{ update_script | quote }} | mysql -u{{mysql_root_user}} -p{{mysql_root_password}} openmrs

- name: Restart openmrs
  service: name=openmrs state=restarted
