# inside .github/workflows/your-action.yml
name: Build RPM and upload to S3 Bucket
on: 
  push:
    branches: [ master, pipeline ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - id: build-RPM
        run: |
          echo '::set-env name=RPM_RELEASE_VERSION::${{ github.run_number }}'
          echo '$RPM_RELEASE_VERSION'
          cd package && ./gradlew buildRpm

      - uses: actions/upload-artifact@v2
        with:
          name: rpm
          path: package/build/distributions/bahmni-covid19-installer-0.92-${{ github.run_number }}.noarch.rpm
      - name: Upload file to bucket
        uses: zdurham/s3-upload-github-action@master
        with:
          args: --acl public-read
        env:
          FILE: package/build/distributions/bahmni-covid19-installer-0.92-${{ github.run_number }}.noarch.rpm
          AWS_REGION: 'us-east-2'
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}